buckket/twtxt

twtxt/cli.py, twtxt/config.py, twtxt/helper.py
Added support for specifying the direction in which timeline posts are
sorted.
The behaviour is controlled through the timeline_sorting configuration
option under [twtxt] in the config file. It can be ascending or
descending, and defaults to descending if no preference is specified.
The actual sorting is done after retrieving the entire list of tweets by
calling a helper function.
Signed-off-by: Weland Treebark <weland@blinkenshell.org>
=> Sort timeline in ascending or descending order

twtxt/types.py
The default arguments are evaluated when module is loaded the first time. If twtxt is used as a package in another tool all created tweets would have the same `created_at` value - if not passed.
=> Fix default argument evaluation

twtxt/helper.py
Strip whitespaces from tweet message.
This is required for `stdin` to prevent trailing newline. However, I think it's a good idea to strip the tweet message anyway in any case - left and right ...
=> Strip tweet before posting

README.rst
I can expand that if you want, but I figure it has the correct levers so people don't get too stuck with private files, for instance.
=> add an aws s3 publishing example

twtxt/cli.py
This patch implements a porcelain option for the timeline command.
It's similar to the porcelain option of other cli tools like the one of `git status`.
```bash
$ twtxt timeline --porcelain
2016-02-07T11:39:38-08:00       Test
2016-02-07T11:40:51-08:00       Test2
2016-02-07T19:43:07+00:00       foobar
2016-02-07T11:43:43-08:00       foobar2
```
Refers #20 
What about the tab delimiter? Do you prefer another character? i.e. git just uses a space ...
=> Implement porcelain option for timeline command

README.rst
To make the example file copy&paste-able.
thx @tedder in #42 for noticing this.
=> Fixed missing tab in example-file

.travis.yml, Makefile
I would like to run `make test` locally to test against all supported python versions.
- Use tox inside Makefile
- Use pytest directly for travis
=> Use tox in make test

Makefile
See http://pythonwheels.com/ for further information
A `setup.cfg` is not needed because we only deploy for python 3.
=> Publish as wheel package

README.rst, config.example, twtxt/cli.py, twtxt/config.py, twtxt/helper.py
The motivation behind this is that I have 2 laptops which I use frequently, so I'd want to do something like `s3cmd get <remote-file>` to grab the latest official version of my stream before writing and re-uploading. You could also do this with a git repo and have the hook do a `git pull` or whatever (which is what I may end up doing, but for now I'm using an "s3" bucket)
This is 90% done. The remaining 10% I need help with, as I'm not familiar with Click or with python in general.
I want to abort execution if the pre_tweet_hook fails, so we don't end up uploading a stale file (which happened while I was testing this, oops!) but I'm not certain how best to do it. I tried raising a `click.UsageError` but that didn't seem correct. `click.Abort` just prints out "Aborted!" and exits, but …
=> support for a pre_tweet_hook configuration parameter

docs/index.rst, docs/registry.rst
Added documentation for registries (see #28). Currently it only mentions https://registry.twtxt.org, but I would like to add @reednj's http://twtxt.reednj.com and https://twtxtlist.cf if they support the api, too!
=> Added documentation for registries

config.example, docs/user/configuration.rst, twtxt/config.py, twtxt/helper.py, twtxt/models.py
Use an absolute datetime for tweet timestamp in timeline per default as suggested in #90 
Make relative timestamps configurable with `use_rel_datetime`.
=>  Make use of absolute time configurable for timeline

docs/user/usage.rst, twtxt/cli.py, twtxt/helper.py
This command behaves similar to other `config` CLI commands
for example the one from git:
``` bash
$ twtxt config twtxt.nick tuxtimo  # set nick
$ twtxt config twtxt.nick  # get nick
tuxtimo
$ twtxt config --remove twtxt.nick  # remove nick
$ twtxt config --edit  # edit config file with editor
```
=> Add config CLI command to edit twtxt config file

docs/user/usage.rst, setup.py, twtxt/cli.py, twtxt/helper.py
Support `--since` option in timeline and view cli command.
The `dateparser` package is used to parse the *since date*: https://pypi.python.org/pypi/dateparser
Examples:
```
twtxt timeline --since yesterday
twtxt timeline --since "1 hour ago"
twtxt view --since "Fri, 12 Dec 2014 10:55:50"
```
=> Support --since option for timeline and view cli command

docs/user/registry.rst, docs/user/twtxtfile.rst
I just changed the documentation in doc/ and haven't touched any code. You probably want to allow more formats in the user facing code?
=> Replace ISO 8601 with RFC 3339 (resolves #103)

README.rst
I believe `date +%FT%T%:z` is exactly the same as writing `date -Isecond`, just more complicated. They are both the same format, and you can run them at the same time and get the exact same result.
Relevant section of `man date`:
-I[FMT], --iso-8601[=FMT]
output date/time in ISO 8601 format.  FMT='date' for  date  only
(the  default),  'hours', 'minutes', 'seconds', or 'ns' for date
and    time    to    the    indicated    precision.     Example:
2006-08-14T02:34:56-0600
=> Simplify `date` command

README.rst
Reverts buckket/twtxt#129
As @jomo pointed out, the `-I` flag is not present in BSD implementations, or in the POSIX standard.
=> Revert "Simplify `date` command"

docs/user/installation.rst
This pull request amends the installation instructions with the option to use `pipx`, a `npx`-style local installer for Python3.
=> Update local installation options

twtxt/cli.py
The missing `cache_interval` argument causes an exception when attempting to unfollow a user, as per #141. This PR should fix that.
=> Add missing cache_interval argument

twtxt/helper.py
A 'twtxt following' call can fail with the following stack trace:
Traceback (most recent call last):
File "/home/marado/.local/bin/twtxt", line 10, in <module>
sys.exit(main())
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
return …
=> bugfix: don't assume that status has status_code

twtxt/twhttp.py
`twtxt following` can err out with the following stack trace:
```
Traceback (most recent call last):
File "/home/marado/.local/bin/twtxt", line 10, in <module>
sys.exit(main())
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/marado/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
return …
```
=> Don't assume that HTTP status has last_modified

README.rst
[twtxt.tcl](https://gitlab.com/dbohdan/twtxt.tcl) is a project that consists of a Tcl library for parsing twtxt, a GUI-based (Tk) twtxt feed reader, an RSS-to-twtxt feed converter, and a utility for extracting mentions from a twtxt feed.
=> README: add link to twtxt.tcl

README.rst
I rewrote my registry server from scratch to be a cleaner/simpler codebase and add a JSON API to complement the plain API from the spec. I'm just swapping the link out here. It still needs work but it's usable and less buggy than the old one.
=> Link to getwtxt-ng registry server instead of deprecated getwtxt.

AUTHORS, setup.py, tox.ini, twtxt/cache.py, twtxt/cli.py, twtxt/helper.py, twtxt/models.py, twtxt/twhttp.py
**Problem:** Generator-based coroutines are deprecated and scheduled for removal in Python 3.11 ([docs](https://docs.python.org/3/library/asyncio-task.html#generator-based-coroutines)). Due to that, twtxt doesn't work with Python 3.7+.
**Solution:** I have changed gererator-based coroutines to async-def coroutines. Other dependencies have also been updated to current versions.
Important: breaking changes, won't work with Python 3.6 or lower.
Passed tests: https://github.com/win0err/twtxt/actions/runs/2009500872
I'll create a PR with integration with GitHub Actions in a separate PR.
Closes #140, closes #141, closes #161, closes #162, closes #163
P.S. Please, test the changes manually.
=> Add support of Python 3.7+

twtxt/cli.py
* Import "get_terminal_size" from "shutil", not "click"
=> Fix compatibility with click >= 8.1.0

README.rst
The old mdom's `we-are-twtxt` repository is no longer available, but yarn.social kept maintaining a fork of it for a good while. It is currently archived, but still available on the address this commit changes the link to.
I'm not sure, but it might make more sense to just remove this enrtry altogether, since the list is no longer maintained and the link only points to an archive.
=> README: we-are-twtxt moved on
